### ISSUE TITLE
Support a form of network browsing

### ISSUE THREAD

**Issue by illiminable** [GoogleChrome/chromeos_network_file_share#10]
This could be just adding something like a default 'Network Neighborhood' share that has eg. servers at the top level etc. Or it could be putting a browse button on the mount dialog that gives you share choices.

Perhaps the latter is better for now at least until other perf issues with large highly nested shares are fixed.

**Comment by illiminable** [comment]
This adds the functionality - but no UI surfaces yet.

https://github.com/GoogleChrome/chromeos_network_file_share/pull/31

**Comment by illiminable** [comment]
See if a simple first pass at this can just populate a drop down on the share path field in the mount dialog.

**Comment by illiminable** [comment]
Currently in V2 because we already have the data and the bug that will show admin/enterprise paths in the dialog is essentially the same that we could maybe copy it. But could be pushed to later.

**Comment by illiminable** [comment]
I'll wait until I'm back in the office on Thursday so I can take a look.

**Comment by allenktv** [comment]
Is this a duplicate of #69?

**Comment by illiminable** [comment]
It's dependent on it but you did them both in the same CL.
