### ISSUE TITLE
Optimize the app package size

### ISSUE THREAD

**Issue by illiminable** [GoogleChrome/chromeos_network_file_share#13]
Right now I think possibly the bower_components folder that is inside the app is redundant. It gets vulcanized into mount_dialog.js/html so shouldn't be needed inside the package.

**Comment by illiminable** [comment]
There's also a bunch of other binaries - essentially /obj output. It's unavoidable that we need to ship both x86 and arm binaries in the same package though.

The way it currently gets packaged just bundles up everything, but ideally the script that generates the package could start with a fresh location and move required items in.

**Comment by allenktv** [comment]
Here are some of the folder and subfolders that were in the megabytes:

- 8.8M	./bower_components
- 56M	./glibc/Release/lib64
- 46M	./glibc/Release/libarm
- 1.3M	./glibc/Release/nacl_fsp_unstripped_arm.nexe
- 1.6M	./glibc/Release/SambaFsp_arm.o

**Comment by allenktv** [comment]
This is whats under `/.lib64`:

- 12M	./libc.so.11835d88
- 2.3M	./libdcerpc-samba.so
- 1.3M	./libm.so.11835d88
- 3.6M	./libnacl_io.so
- 1.6M	./libndr-samba.so
- 5.0M	./libndr-standard.so.0
- 2.5M	./libppapi_cpp.so
- 1.5M	./libpthread.so.11835d88
- 5.5M	./libstdc++.so.6
- 1.1M	./runnable-ld.so

And this is for `libarm`

- 1.1M	./ld-nacl-arm.so.1
- 9.2M	./libc.so.0.1
- 2.2M	./libdcerpc-samba.so
- 1.4M	./libgcc_s.so.1
- 1.9M	./libm.so.0.1
- 3.9M	./libnacl_io.so
- 1.4M	./libndr-samba.so
- 5.0M	./libndr-standard.so.0
- 2.4M	./libppapi_cpp.so
- 1.3M	./libstdc++.so.6

**Comment by illiminable** [comment]
Essentially any .so files are necessary. I think there's a manifest file in the output somewhere that explicitly points to the required libraries. 

Anything .o is a build artifact and shouldn't be in the output. Are they comingled or in different directories? Any other temporary build files are not needed.

You should start by modifying the packaging script to create a new empty directory and selectively add items to it.

What should be required is roughly, the app manifest, any images/icons used by the app, css used by the UI, only the vulcanized outputs (it's just the concatentation of the other files), the .nexe's, and the library/.so output from nacl.

**Comment by allenktv** [comment]
So far, I added a `find -name '*.o' -delete` in `to_temp.sh`. This shrank the package size by about 3MB.

I am not sure how much we can shrink the package by, since most of the space is taken up by `./libarm` and `./lib64` which contain mostly `.so` files. 

Is the idea of #54 where we delete either the `libarm` or `lib64` folder once installed, feasible? I am assuming that isn't ideal, since that doesn't help downloads at all.

**Comment by illiminable** [comment]
No. There's no point deleting after the fact. 3 for the objects and another 9 from the bower components is a good start though.

**Comment by allenktv** [comment]
Just to update the thread. @illiminable and I discussed this and realized that there may be less of what we can do to reduce the size than previously thought. We will consider other options, but for now this will be put on hold. 

I will hold off on submitting my PR that currently only takes off 3 MB of space from `*.o` files
