### ISSUE TITLE
Within share copy is not supported

### ISSUE THREAD

**Issue by illiminable** [GoogleChrome/chromeos_network_file_share#2]
You can copy to or from a share but not within it. The version of Samba currently being used doesn't support server side copy. To implement now would be copying the file from the server to client and back again.

Preferable to upgrade Samba version but need to investigate whether this feature is only supported in some versions of SMB. Worst case the brute force method could be implemented.

**Comment by schultzter** [comment]
That explains my experience! Having this implemented would be awesome!!!
