### ISSUE TITLE
Errors when acessing RO files 

### ISSUE THREAD

**Issue by cottonwool** [GoogleChrome/chromeos_network_file_share#35]
I can't copy or access files that are marked Read Only.
Removing the RO flag and the files can be accessed immediately

Connected to a share on a Windows 7 PC.
The share required a username and password.
The share is RW. I can copy files from local storage to the SMB share.

Can browse some files, copy to local storage and open them using the picture viewer and music player.

Tried to copy other files that were read-only and get errors, 

"Copy  operation failed. The file could not be modified."

and from the console

NACL ERROR: Error performing openFile:smbc_open: errno=13 errtxt=Permission denied
log.js:68 ERROR: rejecting message 915 ACCESS_DENIED
log.js:68 ERROR: openFile rejected promise
log.js:24 NACL ERROR: Error performing openFile:smbc_open: errno=13 errtxt=Permission denied

When trying to copy the RO file from smb to local storage the file is created on local storage but has zero size and the above error message appears.

Also when I try to open RO image I get an error message "This file could not be displayed."

Trying to play a RO music file it appears to be opened by the music player, the name is displayed, but it does not play and eventually skips to the next file which also doesn't play (is also RO.).

Same problem occurs on a RW shared on a Fritz Box 3370 modem/router

Version 50.0.2661.103 (64-bit)
Platform 7978.74.0 (Official Build) stable-channel falco
Firmware Google_Falco.4389.92.0

**Comment by illiminable** [comment]
It's due to the below - but I IIRC I had a problem passing read only here, but I will try and revist this scenario again.

https://github.com/GoogleChrome/chromeos_network_file_share/blob/master/nacl/SambaFsp.cc#L418

**Comment by cottonwool** [comment]
I have previously been using Yoichiro Tanaka's Filesystem for Windows which doesn't have this bug.  I suspect your code is significantly different because, if I understand correctly, you are using ported C/C++ code with the NaCL and Yoichiro is just Javascript. So no cut'n'paste solution here.

**Comment by illiminable** [comment]
Yes it's totally different code. I'll investigate and report back.

**Comment by fortran77** [comment]
I am encountering a similar problem with files exported by a DVR that has a built-in samba file server. After mounting the directory tree exported by the DVR onto a machine that uses the Network File Share for Chrome OS extension, exported files cannot be read by the Chrome OS Files app. The error message is the same as reported above, i.e., "Copy operation failed. The file could not be modified."

I can, however, use the Chrome OS Files app to rename the exported files.

**Comment by allenktv** [comment]
Fixed with https://github.com/GoogleChrome/chromeos_network_file_share/pull/65
