### ISSUE TITLE
Reported that shares with 1 char name do not work

### ISSUE THREAD

**Issue by illiminable** [GoogleChrome/chromeos_network_file_share#44]
Investigate this. eg \server\x

**Comment by allenktv** [comment]
I tested this out but I couldn't reproduce it. 

My steps:

1. Download an image in client 1, rename it as `1` in `/Downloads`
2. Put it in base folder for nas
3. Check in other chromebook (client 2) to see if file propagated
4. Move the file to another sub folder in nas
5. Check again to see if it properly shared.
6. Rename file to `[].jpg` and open file in client 2 to see if it properly opens.

Am I missing anything in my steps?

**Comment by illiminable** [comment]
Sorry it actually has to be the name of the share.

You need to log into the admin console of the nas and create a new share.

**Comment by illiminable** [comment]
So log into the NAS and create a new share with name 'x'. Then try to mount the share \\server\x

**Comment by allenktv** [comment]
@illiminable I tried your suggestion, however I was still able to create and use a share `\\{server}\x` I was able to successfully read and write a file inside it

**Comment by illiminable** [comment]
OK closing.
