### ISSUE TITLE
Fix performance issues with Samba file system app

### ISSUE THREAD

**Issue by dskaram** [GoogleChrome/chromeos_network_file_share#5]
Issue 1  - Files.app downloads the contents of all image files the first time it sees them attempting to generate a thumbnail. This gives very pathological behaviour for network providers especially in shares heavy with large images.

** Tomasz is looking at stopping this for NETWORK fsps but that will take multiple releases to make it to stable channel.

** Investigating workaround to give broken or hardcoded data uri to prevent it

** Implemented returning a broken data uri which prevents the files app downloading every image in a folder. Once Tomasz implements a fix this can be undone and we can still allow thumbs from EXIF data which is far more lightweight.

** Implication is that images will not have thumbnails on shared drives (that’s what linux does anyway).

** Possible other future fixes;
    ** Have the provider generate thumbs from the content the first time the content is downloaded for real.
    ** In some cases could try to parse the windows thumbs.db file (unknown how successful or reliable that might be - but that’s how windows does it)
    ** (Likely not practical for most users) - Get thumbs generated on the server side.

** Implemented a short term cache to handle this. It prevents ⅔’s of the network round trips. There’s a still an underlying issue in the system that makes this less efficient than it could be.

 Issue 2  - The File.app reads the metadata for each file upon navigation a minimum 2 times and any file that becomes visible in the list a thrid time. For network providers this means 3n network roundtrips which becomes pathological with hundreds or thousands of files.

** In process of implementing a metadata cache in the provider. This will reduce the lookup to one NaCl roundtrip and n network roundtrips. Maybe other potential improvements in future.

**Comment by illiminable** [comment]
Closing this since several fixes in the app and in ChromeOS have fixed the issues discussed here (Chrome >= 50). Any future performance bugs we will track more specifically.
