### ISSUE TITLE
Possibility to save servers

### ISSUE THREAD

**Issue by liltinkerer** [GoogleChrome/chromeos_network_file_share#50]
Does this project accept pull requests?

The app should have basic ability to save mounted servers instead of typing each time everything by hand.

**Comment by illiminable** [comment]
Dupe of #43 

This one should be part of the next update. But yes in general pull requests are accepted however you do have to sign a license agreement. See this previous pull request for what will happen when you submit one - https://github.com/GoogleChrome/chromeos_network_file_share/pull/34
