### ISSUE TITLE
Does this plugin works by mount network filesystem? How can I access the mounted file through command line?

### ISSUE THREAD

**Issue by tran-wang** [GoogleChrome/chromeos_network_file_share#52]
it works fine on my chromebook, great work!
But I have enabled development of my chromebook, can I access these shared file in command line?
I am using crouton, I also want to access these shared file in crouton, is it possible?

**Comment by dskaram** [comment]
This only works through the Files app as it uses special Chrome API that is only available through the Chrome runtime. That runtime is not available via the browser. Why not simply install the libsmbclient and use that from the command line?
