### ISSUE TITLE
Configure samba app by policy	

### ISSUE THREAD

**Issue by dskaram** [GoogleChrome/chromeos_network_file_share#6]
For the enterprise use case, admins need to configure the app with policies e.g. the default share location.

This is crucial for enterprise deployments as the only alternative is fanning out instructions to users via email and that is not a viable alternative in companies, especially large ones where these configurations might differ across deployments.

This is an enterprise feature which is described fully here

https://www.chromium.org/administrators/configuring-policy-for-extensions

**Comment by scre80** [comment]
** Ability to push multiple SMB shares down to different share locations
** Pre define domain field
** Description of SMB Share / Mount
** Push down via a Group Policy
** Generic hostname, with user to input share name, ID and password
** Long Term, SSO for seamless access

**Comment by illiminable** [comment]
For first iteration - this will just allow the policy to specify a fixed list of urls, and those urls will appear in the new share selection/input combo box.

Keep the bug open after the initial commits for further iterations.
