### ISSUE TITLE
Improve sequential read of SMB file share app	

### ISSUE THREAD

**Issue by dskaram** [GoogleChrome/chromeos_network_file_share#8]
1. Install SMB file share app.
2. Open a 5-10 MB file.

Downloading and opening the file takes more time than expected.

**Comment by illiminable** [comment]
Reads are now streamed so should be improved. Performance is "OK". Closing this for now - if there are further improvements those will be tracked separately.

Only obvious next fix is to read ahead in parallel on the NaCl side.
